all:
	$(CC) src\brainfuck.c src\main.c /Fe:brainfuck.exe

test:
	$(CC) /Fe:brainfuck_tests.exe /Isrc tests\tests.c src\brainfuck.c
	brainfuck_tests.exe

sdl:
	$(CC) src\brainfuck.c src\sdl.c SDL2.lib SDL2main.lib /DDIRECT_SDL_INCLUDE /Fe:brainfuck_sdl.exe /link /SUBSYSTEM:CONSOLE
